version: 0.1

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ${IMAGE_NAME} .
      - docker tag ${IMAGE_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/develop/${IMAGE_NAME}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/develop/${IMAGE_NAME}:${IMAGE_TAG}
